Spice/Areas/Admin/Controllers/CouponController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Models.ViewModel;
using Spice.Utility;
using System.Data;

namespace Spice.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = SD.ManagerUser)]

	public class CouponController : Controller
	{
		private readonly ApplicationDbContext _db;
		public CouponController(ApplicationDbContext db)
		{
			_db = db;
		}

		[BindProperty]
		public Coupon coupons { get; set; }

		public async Task<IActionResult> Index()
		{
			var couponOrder = await _db.Coupon.ToListAsync();
		    var coupon =  from a in couponOrder
							   orderby a.Discount
						   select a;
			return View(coupon);  
		}

		//GET-Create
		[HttpGet]

		public async Task<IActionResult> Create()
		{
			return View();
		}

		//Post-Create

		[HttpPost, ActionName("Create")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreatePost()
		{
			if (!ModelState.IsValid) //not work
			{
				var files = HttpContext.Request.Form.Files;
				if (files.Count > 0)
				{
					byte[] p1 = null;
					using (var fs1 = files[0].OpenReadStream())
					{
						using (var ms1 = new MemoryStream())
						{
							fs1.CopyTo(ms1);
							p1 = ms1.ToArray();
						}
					}
					coupons.Picture = p1;
				}
			}
			_db.Coupon.Add(coupons);
			await _db.SaveChangesAsync();

			return RedirectToAction(nameof(Index));
		}

		//GET-Edit
		[HttpGet]

		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var coupon = await _db.Coupon.SingleOrDefaultAsync(M => M.Id == id);
			if (coupon == null)
			{
				return NotFound();
			}
			return View(coupon);
		}

		//Post-Edit

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit()
		{
			if (coupons.Id == 0)
			{
				return NotFound();
			}

			var couponFromDb = await _db.Coupon.Where(c => c.Id == coupons.Id).FirstOrDefaultAsync();

			if (!ModelState.IsValid)
			{
				var files = HttpContext.Request.Form.Files;
				if (files.Count > 0)
				{
					byte[] p1 = null;
					using (var fs1 = files[0].OpenReadStream())
					{
						using (var ms1 = new MemoryStream())
						{
							fs1.CopyTo(ms1);
							p1 = ms1.ToArray();
						}
					}
					couponFromDb.Picture = p1;
				}
				couponFromDb.MinimumAmount = coupons.MinimumAmount;
				couponFromDb.Name = coupons.Name;
				couponFromDb.Discount = coupons.Discount;
				couponFromDb.CouponType = coupons.CouponType;
				couponFromDb.IsActive = coupons.IsActive;

				await _db.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(coupons);
		}

		//GET-Details
		[HttpGet]

		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var coupon = await _db.Coupon.SingleOrDefaultAsync(M => M.Id == id);
			if (coupon == null)
			{
				return NotFound();
			}
			return View(coupon);
		}

		//Post-Details

		[HttpPost, ActionName("Details")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DetailsPost()
		{
			if (coupons.Id == 0)
			{
				return NotFound();
			}

			var couponFromDb = await _db.Coupon.Where(c => c.Id == coupons.Id).FirstOrDefaultAsync();

			if (!ModelState.IsValid) //not work
			{
				var files = HttpContext.Request.Form.Files;
				if (files.Count > 0)
				{
					byte[] p1 = null;
					using (var fs1 = files[0].OpenReadStream())
					{
						using (var ms1 = new MemoryStream())
						{
							fs1.CopyTo(ms1);
							p1 = ms1.ToArray();
						}
					}
					couponFromDb.Picture = p1;
				}

				couponFromDb.MinimumAmount = coupons.MinimumAmount;
				couponFromDb.Name = coupons.Name;
				couponFromDb.Discount = coupons.Discount;
				couponFromDb.CouponType = coupons.CouponType;
				couponFromDb.IsActive = coupons.IsActive;

				await _db.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(coupons);
		}


		//GET-Delete
		[HttpGet]

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var coupon = await _db.Coupon.SingleOrDefaultAsync(M => M.Id == id);
			if (coupon == null)
			{
				return NotFound();
			}
			return View(coupon);
		}

		//Post-Delete

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeletePost(int id)
		{
			var couponDelete = await _db.Coupon.SingleOrDefaultAsync(m=> m.Id == id);
			_db.Coupon.Remove(couponDelete);
			await _db.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
	}
}

Spice/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Utility;
using System.Data;
using System.Security.Claims;

namespace Spice.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = SD.ManagerUser)]

	public class UserController : Controller
	{
		private readonly ApplicationDbContext _db;
		public UserController(ApplicationDbContext db)
		{
			_db = db;
		}

		public async Task<IActionResult> Index()
		{
			var claimsIdentity = (ClaimsIdentity)this.User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			var user = await _db.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync();
			var userOrder =  from a in user
							 orderby a.Name 
							 select a;


            return View(userOrder);
		}

		//Lock
		public async Task<IActionResult>Lock(string id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
			if (applicationUser == null)
			{
				return NotFound();
			}
			applicationUser.LockoutEnd = DateTime.Now.AddDays(7);
			await _db.SaveChangesAsync();
			
			return RedirectToAction(nameof(Index));
		}

		//Unlock
		public async Task<IActionResult> Unlock(string id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
			if (applicationUser == null)
			{
				return NotFound();
			}
			applicationUser.LockoutEnd = DateTime.Now;
			await _db.SaveChangesAsync();

			return RedirectToAction(nameof(Index));
		}
	}
}

Spice/Views/Shared/_CreateAndBacktoListButton.cshtml
<div class="row">
	<div class="col-6">
		<input type="submit" value="Create" class="btn btn-info text-white form-control" />
	</div>
	<div class="col-6">
		<a asp-action="Index" class="btn btn-success form-control">Back To List</a>
	</div>
</div>

Spice/Views/Shared/_CreateButtonPartial.cshtml
<p>
	<a asp-action="Create" class="btn btn-info text-white"><i class="fa-solid fa-plus"></i> &nbsp; Create New</a>
</p>

Spice/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
	<div class="col-6">
		<input type="submit" class="btn btn-danger form-control text-white" asp-route-id="@Model" value="Delete" />
	</div>
	<div class="col-6">
		<a asp-action="Index" class="btn btn-success form-control">Back To List</a>
	</div>
</div>

Spice/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
	<div class="col-6">
		<a asp-action="Edit" asp-route-id="@Model" class="btn btn-info text-white form-control">Edit</a>
	</div>
	<div class="col-6">
		<a asp-action="Index" class="btn btn-success form-control">Back To List</a>
	</div>
</div>

Spice/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
	<div class="col-6">
		<input type="submit" class="btn btn-info form-control text-white" asp-route-id="@Model" value="Update" />
	</div>
	<div class="col-6">
		<a asp-action="Index" class="btn btn-success form-control">Back To List</a>
	</div>
</div>

Spice/Views/Shared/_IndividualOrderDetails.cshtml
@using Spice.Utility;
@model Spice.Models.ViewModel.OrderDetailsViewModel

<form method="post" asp-action="PickUpOrder" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.Id">
	<div class="container row border ml-1 backgroundWhite10Padding" style="width:100%;">

		<div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
			<br />
			<input type="hidden" asp-for="OrderHeader.Id" />

			<div class="form-group row">
				<div class="col-3">
					<label>Name</label>
				</div>
				<div class="col-9">
					<input asp-for="OrderHeader.PickupName" disabled class="form-control" />
				</div>
			</div>
			<br />

			<div class="form-group row">
				<div class="col-3">
					<label asp-for="OrderHeader.ApplicationUser.Email"></label>
				</div>
				<div class="col-9">
					<input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
				</div>
			</div>
			<br />

			<div class="form-group row">
				<div class="col-3">
					<label asp-for="OrderHeader.ApplicationUser.PhoneNumber"></label>
				</div>
				<div class="col-9">
					<input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
				</div>
			</div>
			<br />

			<div class="form-group row">
				<div class="col-3">
					<label asp-for="OrderHeader.OrderTotal"></label>
				</div>
				<div class="col-9">
					<input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
				</div>
			</div>
			<br />

			<div class="form-group row">
				<div class="col-3">
					<label asp-for="OrderHeader.OrderDate"></label>
				</div>
				<div class="col-9">
					<input value="@Model.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
				</div>
			</div>
			<br />

			<div class="form-group row">
				<div class="col-3">
					<label asp-for="OrderHeader.Comments"></label>
				</div>
				<div class="col-9">
					<input asp-for="OrderHeader.Comments" disabled class="form-control" />
				</div>
			</div>
			<br />
		</div>

		<div class="col-lg-4 col-12">

			<h4 class="d-flex justify-content-between align-content-center mb-3 mt-3">
				<span class="text-muted">Order Id: </span>
				<span class="badge rounded-pill bg-secondary">@Model.OrderHeader.Id</span>
			</h4>

			<ul class="list-group mb-3">

				@foreach (var details in Model.OrderDetails)
				{
					<li class="list-group-item d-flex justify-content-between">
						<div>
							<h6 class="my-0">@details.Name</h6>
							<small class="text-muted">Quantity : @details.Count</small>
						</div>
						<span class="text-muted">@(details.Price * details.Count)</span>

					</li>
				}

				@if (Model.OrderHeader.CouponCode != null)
				{
					<li class="list-group-item d-flex justify-content-between">
						<div class="text-success">
							<h6 class="my-0">Promo Code</h6>
							<small class="text-muted">@Model.OrderHeader.CouponCode</small>
						</div>
						<span class="text-success">@(Model.OrderHeader.OrderTotalOriginal - Model.OrderHeader.OrderTotal)</span>
					</li>
				}

				<li class="list-group-item d-flex justify-content-between bg-light">
					<span class="text-info fw-bolder">Total(USD)</span>
					<strong class="text-info fw-bolder">$@Model.OrderHeader.OrderTotal</strong>
				</li>
			</ul>
			@if (Model.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser)))
			{
				<button class="btn btn-success text-white form-control" type="submit">
					<i class="far fa-thumbs-up"></i> Confirm Pickup
				</button>
			}
			else
			{
				<button class="btn btn-info text-white form-control" type="submit" disabled>
					@Model.OrderHeader.Status
				</button>
			}
		</div>

	</div>
</form>

Spice/Views/Shared/_Layout.cshtml
@using Spice.Utility;
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Spice</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Spice.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/jquery-ui.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.14.0/jquery.timepicker.css" />

</head>
<body class="search-background">
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
					<img src="~/images/mild.png" />
					<img src="~/images/spicy.png" />
					<img src="~/images/verySpicy.png" />
					<label class="text-info" style="cursor:pointer;">Spice</label>
				</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">

						@if (User.IsInRole(SD.ManagerUser))
						{
							<li class="nav-item dropdown text-white-50">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Content Management
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
									<a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
									<a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
									<a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">MenuItem</a>
									<a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
									<a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Users</a>
								</div>
							</li>
						}

						@if (User.IsInRole(SD.ManagerUser) | User.IsInRole(SD.CustomerEndUser) | User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser))
						{
							<li class="nav-item">
								<a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
									Order History
								</a>
							</li>

						}

						@if (User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.ManagerUser))
						{
							<li class="nav-item dropdown text-white-50">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropDown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Order
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
									@if (User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser))
									{
										<a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Manage Order</a>
									}
									@if (User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.ManagerUser))
									{
										<a class="dropdown-item" asp-action="PickUpOrder" asp-controller="Order" asp-area="Customer">Order Pickup</a>
									}
								</div>
							</li>
						}


						@if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount) != null)
						{
							<li style="color:white;">
								<a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
									@{
										var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount);
									}
									<i class="fas fa-shopping-cart"></i> &nbsp; (@count)
								</a>
							</li>
						}
						else
						{
							<li style="color:white;">
								<a href="#" class="nav-link">
									<i class="fas fa-shopping-cart"></i> &nbsp; (0)
								</a>
							</li>
						}
					</ul>

					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40;">
		<div class="container">
			&copy; Powered By - Smit Chhatrola (2022)
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/jquery-ui.js"></script>

	<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp"></script>
	<script src="https://kit.fontawesome.com/be883cb128.js" crossorigin="anonymous"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Spice/Views/Shared/_OrderStatus.cshtml
@model string
@using Spice.Utility


<div style="width:100%">

    @if (Model == SD.StatusSubmited)
    {
        <img src="~/images/OrderPlaced.png" width="100%" />
    }
    @if (Model == SD.StatusInProcess)
    {
        <img src="~/images/InKitchen.png" width="100%" />
    }
    @if (Model == SD.StatusReady)
    {
        <img src="~/images/ReadyForPickup.png" width="100%" />
    }
    @if (Model == SD.StatusCompleted)
    {
        <img src="~/images/completed.png" width="100%" />
    }
</div>

Spice/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}

Spice/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
	<div class="btn-group" role="group">
		<a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
			<i class="fa fa-edit"></i>
		</a>

		<a class="btn btn-successtext-white" asp-action="Details" asp-route-Id="@Model">
			<i class="fas fa-list-alt"></i>
		</a>

		<a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
			<i class="fa fa-trash-alt"></i>
		</a>

	</div>
</td>

Spice/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>

@if (Model.Count() > 0)
{
	<div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">
		<div class="row">
			<h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
		</div>

		@foreach (var item in Model)
		{
			<div class="border border-info rounded col-12" style="margin:10px 20px;padding:10px;box-sizing:bor">
				<div class="row">
					<div class="col-md-3 col-sm-12">
						<img src="@item.Image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9;">
					</div>
					<div class="col-md-9 col-sm-12">
						<div class="row pr-3">
							<div class="col-8">
								<label class="text-primary" style="font-size:21px;color:maroon">@item.Name</label>
								@if (item.Spicyness == "1")
								{
									<img srcset="/images/mild.png" title="mild" />
								}
								@if (item.Spicyness == "2")
								{
									<img srcset="/images/spicy.png" title="spicy" />
								}
								@if (item.Spicyness == "3")
								{
									<img srcset="/images/veryspicy.png" title="veryspicy" />
								}
							</div>
							<div class="col-4 text-right" style="color:maroon">
								<h4>$@item.Price</h4>
							</div>
						</div>

						<div class="row col-12 text-start d-none d-md-block">
							<p>@Html.Raw(item.Description)</p>
						</div>
						<div class="col-md-3 col-sm-12 text-center offset-md-9">
							<a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
						</div>
					</div>
				</div>
			</div>
		}
		<div class="p-4"></div>
	</div>
}